version: "3.9"
services:
  ibis_test_base: &ibis_test_base
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/host
    working_dir: /host

  shell:
    <<: *ibis_test_base
    command: /bin/bash
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    links:
      - db
      
  test:
    <<: *ibis_test_base
    command: /usr/local/bin/python ./doit.py
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    links:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
